# Change these first
owner: streamlined-scs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SAM VTR
    url: https://seam.vtr.cl/obtenerListadoActividades?wsdl
  - name: EAM Cencosud
    url: https://eam.cencosud.com/web/base/logindisp?tenant=SCSPROD
  - name: SPP Cencosud
    url: https://seam.cencosud.com/eam/auth/login
  - name: EAM Blumar
    url: https://eambl.blumar.com
  - name: Reporte EAM Blumar
    url: https://eamrpt.blumar.com/birt2/frameset?__report=Blumar_orden_trabajo_prod.rptdesign&__format=pdf
  - name: SAM EndPoint Blumar
    url: https://eamep.blumar.com/api/Scsactividades/getActivitieespecialidad
  - name: EAM Maara
    url: http://eam.maaracorp.com:8081/web/base/logindisp?tenant=EAM
  - name: SEAM Dreams
    url: https://seam-md.streamlined-app.io
  - name: SEAM Highlift
    url: https://seam-hl.streamlined-app.io
  - name: SEAM Grupo America
    url: https://seam-ga.streamlined-app.io
  - name: SEAM Report SEAM PROD
    url: https://seam-rpt.streamlined-app.io/birt/frameset?__report=Scs_orden_trabajo_cliente.rptdesign&__format=PDF
  - name: WSDL SAM Highlift
    url: https://wsdl-hl.streamlined-app.io/api/Scsdocumentos/getLogo
  - name: WSDL SAM Grupo America
    url: https://wsdl-ga.streamlined-app.io/api/Scsdocumentos/getLogo
  - name: WSDL SAM Dreams
    url: https://wsdl-md.streamlined-app.io/api/Scsdocumentos/getLogo
  - name: WSDL Maara Mobile SAT
    url: http://eam.maaracorp.com:8083/WsseamSAT/WSEAMC/ws/ObtenerOrdenesdetrabajo?EVT_PERSON=4205  
  - name: WSDL Cencosud Mobile SAM
    url: https://seam.cencosud.com/WsseamPROD/WSEAMC/ws/ObtenerEquipos?OBJ_MRC=E585&OBJ_ESPE=TV
  - name: WSDL Cencosud Reportes
    url: https://seam.cencosud.com/birt/frameset?__report=SCS_reporte_orden_compra_prod.rptdesign&__format=PDF&ORDERCODE=235883    
  - name: Pagina Web Streamlined
    url: https://streamlined.cl
  - name: Correo Streamlined
    url: https://www.streamlined.cl/webmail/log-in
  - name: Central Telefonica Streamlined
    url: https://freepbx.streamlined-scs.cl/admin/config.php
  - name: NAS Streamlined
    url: https://nas.streamlined-scs.cl
  - name: Workspace Streamlined
    url: https://workspace.streamlined-scs.cl
  - name: SMGI Metabase Streamlined
    url: https://mgi.streamlined-scs.cl
  - name: GITLAB Streamlined
    url: https://gitlab.streamlined-scs.cl/users/sign_in
  - name: WIKI SCS Streamlined
    url: https://wikijs.streamlined-scs.cl/login
  - name: Meet Jitsi Streamlined
    url: https://jitsi.streamlined-scs.cl
  - name: Element Streamlined
    url: https://element.streamlined-scs.cl/
  - name: Matrix Streamlined
    url: https://matrix.streamlined-scs.cl
  - name: SEAM SCS Demo
    url: https://seam-demo.streamlined-scs.cl/web/base/logindisp?tenant=SEAMXIII
  - name: WSDL SAM SCS Demo
    url: https://wsdl-demo.streamlined-scs.cl/api/Scssalidabodega/getcontadorsalidabodega
  - name: SEAMX SCS Desa
    url: https://seam-admin-dev.streamlined-scs.cl/auth/login
  - name: EAM Maara Desa
    url: https://maara.streamlined-scs.cl/web/base/logindisp?tenant=EAM
  - name: SAT Maara Desa
    url: https://ws-sat.streamlined-scs.cl/WsseamSAT/WSEAMC/ws/ObtenerEmpleado?MRC_CODE=RG-FAJ
  - name: EAM Cencosud Desa
    url: https://eam-cencodesa.streamlined-scs.cl/web/base/logindisp?tenant=SCSPROD 
  - name: WSDL SAM Cencosud Desa
    url: https://ws-cenco-sam.streamlined-scs.cl/WsseamPROD/WSEAMC/ws/ObtenerEquipos?OBJ_MRC=E585&OBJ_ESPE=TV
  - name: SPP Cencosud Desa
    url: https://spp-cenco.streamlined-scs.cl/auth/login
  - name: EAM Blumar Desa
    url: https://eam-blumar.streamlined-scs.cl/web/base/logindisp

assignees:
- streamlined-scs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://streamlined.cl/logos/logo%20SCS1.png
  name: Streamlined SCS Upptime
  introTitle: "**Upptime Streamlined** es nuestra web de control upptime de Servicios Web, powered entirely by GitHub."
  introMessage: Esta es una pagina que representa el estado de **UPTIME** de nuestros servicios **real-time**
  navbar:
    - title: Status Streamlined SCS
      href: https://streamlined.cl
    - title: GitHub Streamlined SCS 
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
