# Change these first
owner: streamlined-scs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pagina Web Streamlined
    url: https://streamlined.cl
  - name: Central Telefonica Streamlined
    url: https://freepbx.streamlined-scs.cl/admin/config.php
  - name: NAS Streamlined
    url: https://nas.streamlined-scs.cl
  - name: Workspace Streamlined
    url: https://workspace.streamlined-scs.cl
  - name: SMGI Metabase Streamlined
    url: https://mgi.streamlined-scs.cl
  - name: GITLAB Streamlined
    url: https://gitlab.streamlined-scs.cl/users/sign_in
  - name: SMGI Grafana Streamlined
    url: https://smgi.streamlined-scs.cl/login
  - name: EAM Cencosud
    url: https://eam.cencosud.com/web/base/logindisp?tenant=SCSPROD
  - name: EAM Maara
    url: http://eam.maaracorp.com:8081/web/base/logindisp?tenant=EAM
  - name: EAM Blumar
    url: http://eam.blumar.com/web/base/logindisp?tenant=EAMPROD
  - name: SEAM Dreams
    url: https://seam-md.streamlined-scs.cl
  - name: SEAM Highlift
    url: https://seam-hl.streamlined-scs.cl
  - name: SEAM Grupo America
    url: https://seam-ga.streamlined-scs.cl
  - name: WSDL SAM Highlift
    url: https://wsdl-hl.streamlined-scs.cl/api/Scsdocumentos/getLogo
  - name: WSDL SAM Grupo America
    url: https://wsdl-ga.streamlined-scs.cl/api/Scsdocumentos/getLogo
  - name: WSDL SAM Dreams
    url: https://wsdl-md.streamlined-scs.cl/api/Scsdocumentos/getLogo
  - name: WSDL Maara Mobile SAT
    url: http://eam.maaracorp.com:8083/WsseamSAT/WSEAMC/ws/ObtenerOrdenesdetrabajo?EVT_PERSON=4205  
  - name: WSDL Cencosud Mobile SAM
    url: https://seam.cencosud.com/WsseamPROD/WSEAMC/ws/ObtenerEquipos?OBJ_MRC=E585&OBJ_ESPE=TV
  - name: WSDL Cencosud Reportes
    url: https://seam.cencosud.com/birt/frameset?__report=SCS_reporte_orden_compra_prod.rptdesign&__format=PDF&ORDERCODE=235883
  - name: Meet Jitsi Streamlined
    url: https://jitsi.streamlined-scs.cl

assignees:
- streamlined-scs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://streamlined.cl/logos/logo%20SCS1.png
  name: Streamlined SCS Upptime
  introTitle: "**Upptime Streamlined** es nuestra web de control del upptime de paginas, powered entirely by GitHub."
  introMessage: Esta es una pagina que representa el estado de una pagina en **real-time**
  navbar:
    - title: Status SCS Chile
      href: https://streamlined.cl
    - title: GitHub SCS
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
